---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:querydsl-in-action;
    driver-class-name: org.h2.Driver
    username: abc
    password: abc
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
---